### ISSUE TITLE
Where to download the AMR 2/3 release datasets 

### ISSUE THREAD

**Issue by alice-cool** [Wangpeiyi9979/HCL-Text2AMR#1]

**Comment by alice-cool** [comment]
File "/home/byd/HCL-Text2AMR/spring_amr/IO.py", line 12, in read_raw_amr_data
    assert paths
AssertionError

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/170515857-3fcb0601-592f-4f6f-a2c7-6a99efc8de9e.png)

**Comment by Wangpeiyi9979** [comment]
Hello, the AMR dataset is not free, you can buy it from LDC:

AMR2.0: https://catalog.ldc.upenn.edu/LDC2017T10.
AMR3.0: https://catalog.ldc.upenn.edu/LDC2020T02.

**Comment by alice-cool** [comment]
Thanks for your timely reply.&nbsp;



---原始邮件---
发件人: "Peiyi ***@***.***&gt;
发送时间: 2022年5月26日(星期四) 晚上11:47
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [Wangpeiyi9979/HCL-Text2AMR] Where to download the AMR 2/3 release datasets  (Issue #1)




 
Hello, the AMR dataset is not free, you can buy it from LDC:
 
AMR2.0: https://catalog.ldc.upenn.edu/LDC2017T10.
 AMR3.0: https://catalog.ldc.upenn.edu/LDC2020T02.

**Comment by Wangpeiyi9979** [comment]
you are welcome. 😊
